version: '3.1'

services:
  config:
    container_name: config-server
    restart: always
    environment:
      CONFIG_SERVER_PORT: 8888
      CONFIG_SERVICE_USER_PASSWORD: user
      CONFIG_SERVICE_USER_NAME: password
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"

  eureka:
    container_name: eureka-server
    restart: always
    environment:
      EUREKA_SERVER_PORT: 8761
      CONFIG_SERVER_URL: http://config:8888
      CONFIG_SERVICE_USER_PASSWORD: user
      CONFIG_SERVICE_USER_NAME: password
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  auth:
    container_name: auth-service
    restart: always
    environment:
      CONFIG_SERVER_URL: http://config:8888
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
    - "8600:8600"
