version: '3.1'

services:
  config:
    restart: always
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    links:
      - registry

  registry:
    restart: always
    build:
      context: ./registry-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  gateway:
    restart: always
    build:
      context: ./gateway-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  auth-service:
    restart: always
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      ACCOUNT_SERVICE_PASSWORD: password
    ports:
      - "8600:8600"
    depends_on:
      - auth-mongodb

  auth-mongodb:
    restart: always
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_USERNAME: user
      MONGO_INITDB_PASSWORD: password
      MONGO_INITDB_DATABASE: pomodorogo
    ports:
      - "27017:27017"

  account-service:
    restart: always
    build:
      context: ./account-service
      dockerfile: Dockerfile
    ports:
      - "8601:8601"
    depends_on:
      - account-mongodb

  account-mongodb:
    restart: always
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_USERNAME: user
      MONGO_INITDB_PASSWORD: password
      MONGO_INITDB_DATABASE: pomodorogo
    ports:
      - "27018:27017"