version: '3.1'

services:
  config:
#    container_name: config-server
    restart: always
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    links:
      - registry

  registry:
#    container_name: registry-server
    restart: always
    build:
      context: ./registry-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  gateway:
#    container_name: gateway-server
    restart: always
    build:
      context: ./gateway-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  auth-service:
    container_name: auth-service
    restart: always
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8600:8600"
    depends_on:
      - auth-mongodb

  auth-mongodb:
    restart: always
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_USERNAME: user
      MONGO_INITDB_PASSWORD: password
      MONGO_INITDB_DATABASE: pomodorogo
