version: '3.1'

services:
  config:
    container_name: config-server
    restart: always
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"

  eureka:
    container_name: eureka-server
    restart: always
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    links:
      - config

  gateway:
    container_name: gateway-server
    restart: always
    build:
      context: ./gateway-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - eureka

  auth-service:
    container_name: auth-service
    restart: always
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8600:8600"
    links:
      - eureka

  auth-mongodb:
    restart: always
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_USERNAME: user
      MONGO_INITDB_PASSWORD: password
      MONGO_INITDB_DATABASE: pomodorogo
