version: '3.1'

services:
  config:
    container_name: config-server
    restart: always
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"

  eureka:
    container_name: eureka-server
    restart: always
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - config

  gateway:
    container_name: gateway-server
    restart: always
    build:
      context: ./gateway-server
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    depends_on:
      - config

  auth:
    container_name: auth-service
    restart: always
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
    - "8600:8600"
    depends_on:
      - config
      - eureka
