server:
  port: 8601

spring:
  application:
    name: account-service
  data:
    mongodb:
      host: account-mongodb
      username: user
      password= ${MONGODB_PASSWORD: password}
      database= ${MONGODB_DATABASE: pomodorogo}
      port: 27017

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
