server:
  servlet:
    context-path: /accounts
  port: ${ACCOUNT_SERVICE_PORT:8601}

spring:
  application:
    name: account-service
  data:
    mongodb:
      host: account-mongodb
      username: ${MONGO_INITDB_USERNAME:user}
      password: ${MONGO_INITDB_PASSWORD:password}
      database: ${MONGO_INITDB_DATABASE:pomodorogo}
      port: ${MONGODB_PORT:27017}

security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD:password}
      accessTokenUri: http://auth-service:8600/uaa/oauth/token
      grant-type: client_credentials
      scope: server
