server:
  port: ${AUTH_SERVICE_PORT:8600}

spring:
  application:
    name: auth-service

eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOSTNAME:registry}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://registry:8761/eureka/}
