server:
  servlet:
    context-path: /uaa
  port: ${AUTH_SERVICE_PORT:8600}

spring:
  application:
    name: auth-service
  data:
    mongodb:
      host: auth-mongodb
      username: ${MONGO_INITDB_USERNAME:user}
      password: ${MONGO_INITDB_PASSWORD:password}
      database: ${MONGO_INITDB_DATABASE:pomodorogo}
      port: ${MONGODB_PORT:27017}
