spring:
  application:
    name: gateway-server

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://registry:8761}/eureka/

server:
  port: ${GATEWAY_SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: "*"